# Generated by Django 4.1.4 on 2023-01-19 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_Name', models.CharField(default=None, max_length=40)),
                ('Author_Name', models.CharField(default=None, max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_Name', models.CharField(default=None, max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stud_Name', models.CharField(default=None, max_length=40)),
                ('Stud_Phn_No', models.BigIntegerField(default=0)),
                ('Stud_Sem', models.IntegerField(default=0)),
                ('Stud_Password', models.CharField(default=None, max_length=40)),
                ('Stud_Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LMSApp.course')),
            ],
        ),
        migrations.CreateModel(
            name='Issue_Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Start_Date', models.DateField()),
                ('End_Date', models.DateField()),
                ('Book_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LMSApp.book')),
                ('Stud_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LMSApp.student')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='Course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LMSApp.course'),
        ),
    ]
